### ISSUE TITLE
create CSS variables for all existing SASS variables

### ISSUE THREAD

**Issue by amirhosseinab** [violaui/typography#1]
By creating CSS variables, everyone who wants to use the generated CSS only can customize the classes.

For example:

```css
:root {
   --sans-serif: Roboto;
}

.sans-serif {
   font-family: var(--sans-serif);
}
```
